
language: go
go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip
install:
  - go get github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
  - glide install
script:
  - go build