kind: ConfigMap
apiVersion: v1
metadata:
  name: kapacitor-hpa-rule-identity
  namespace: eng
data:
  # default tick template
  template: "autoscaling"
  # target is the desired number of request per second per host
  target: "11.0"
  # only one scaling event will be triggered by this time interval
  # https://docs.influxdata.com/kapacitor/v1.3/tick/syntax/#durations
  scalingCooldown: 1m
  # only one descaling even twill be triggered by this time interval
  # https://docs.influxdata.com/kapacitor/v1.3/tick/syntax/#durations
  descalingCooldown: 2m
  # database
  database: telegraf
  # retention policy for database
  retentionPolicy: 2-weeks
  # dataset collected within the retention policy
  measurement: docker_container_cpu
  # data to be used for comparison with target
  field: usage_percent
  # comparison used between dataPoint and target
  # valid ones are < (less than) or > (greater than)
  comparisonOperator: <
  # name of deployment to scale for
  deploymentName: bump-proxy-qa-xo-app-manifest
  # name of release
  releaseName: bump-proxy-qa